name: "Build and Deploy to Hostinger"
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Install dependencies
        run: npm install
 
      - name: Build
        run: npm run build

      - name: Create public_html structure
        run: |
         mkdir -p public_html
         cp -r dist/* public_html/
 
      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_html

          publish_branch: build



